# Generated by Django 4.0.4 on 2022-06-13 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_register_first_name_alter_register_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=30)),
                ('litres', models.IntegerField(default=15)),
                ('bottles', models.IntegerField(default=15)),
            ],
        ),
    ]
